version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backeend-app
    ports:
      - 3004:3002
    volumes:
      - ./:/home/app/
    networks:
      - app-network

  Backenddb:
    image: mysql:8.0.21
    container_name: backeend-db
    environment:
      MYSQL_ROOT_PASSWORD: 4321
    ports:
      - 3309:3306
    volumes:
      - colab-v2_volume_db:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  colab-v2_volume_db: {}
